Contact form
Ngufor-emmanuella/my-first-portfo pull request #5
Opened 2022-05-05 09:58 UTC by Ngufor-emmanuella

- 
**Add Contact form**

- Add the name field that  accepts up to 30 characters.
-  Add the email field that accepts only emails.
- Add the text area that accepts up to 500 characters
- All fields have placeholder text.
- A user cannot submit the form if one or more of the fields is empty.
- Collect data by using the [Formspree service](https://formspree.io/html).
- Add Interactions on the submit button

**Update Readme file**

- Add authors

2022-05-05 13:30 UTC, danmainah requested changes
Hi @Ngufor-emmanuella, @AbbyNyakara  and @Bornittah, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


# Required Changes ♻️

- [ ] Great job team especially with the design, there is a small error in your current form kindly check the comparison below and fix it.

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/166932594-9e64cbe7-54b1-44a8-bf2d-569a4eadd1ce.png) | ![image](https://user-images.githubusercontent.com/61408860/166933217-5f33cd67-76f0-4b80-8fb7-aabd6754ce3d.png)

- [ ] Kindly make sure the hover effect in your buttons follow the design given, below is the colors in the design given:
![image](https://user-images.githubusercontent.com/61408860/166933599-3725cc79-8f03-42e1-868b-5658acf7a196.png)




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-05 13:30 UTC, danmainah commented on index.html
> +                        </form>
- [ ] Kindly make sure to use flexbox to style your form elements, this is a project requirement.

2022-05-05 18:13 UTC, codepantha requested changes
Hi @Ngufor-emmanuella @AbbyNyakara and @Bornittah  👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-medium.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 18:13 UTC, codepantha commented on index.html
> +                        </form>
- [ ] As requested by the previous reviewer, please implement the hover state for the button as shown below 👇 
![image](https://user-images.githubusercontent.com/61408860/166933599-3725cc79-8f03-42e1-868b-5658acf7a196.png)

2022-05-05 18:13 UTC, codepantha commented on index.html
> +                        </form>
- [ ] As requested by the previous reviewer, kindly make sure to use flexbox to style your form elements, this is a project requirement 🙏

2022-05-06 10:14 UTC, sja-thedude commented on index.html
> +                        </form>
Good job in implementing the changes 👍

2022-05-06 10:14 UTC, sja-thedude commented on index.html
> +                        </form>
Good job in implementing the changes 👍

2022-05-06 10:15 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @Ngufor-emmanuella, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 10:19 UTC, merged